create table if not exists public.users (
  id bigint generated by default as identity primary key,
  nickname text unique not null,
  password_hash text,
  avatar_url text,
  created_at timestamptz default now()
);
create unique index if not exists users_nickname_ci_key on public.users (lower(nickname));
